version: '3'
services:
  user-api:
    build: user-api/
    ports:
      - 9999:8080
    restart: unless-stopped
    volumes:
      - ./user-api:/var/www

  banking-core:
    build: banking-core/
    ports:
      - 9000:9000
    restart: unless-stopped

    volumes:
      - ./banking-core:/var/www